### ISSUE TITLE
Structs are not serialized properly

### ISSUE THREAD

**Issue by jamietdavidson** [tyronbrand/flow.net#101]
HI,

I am experiencing an error: `invalid argument at index 1: decodeing argument failed: [Error Code: 1052] transaction arguments are invalid: (argument is not json decodable: failed to decode value: invalid JSON Cadence structure)`.

Screenshot of my debugger. What am I missing?
![Screen Shot 2022-09-26 at 3 20 01 PM](https://user-images.githubusercontent.com/80986926/192390728-fc4834c3-96ea-4092-b11e-f41d697ee587.png)

**Comment by tyronbrand** [comment]
Hey,

Could you provide me with a bit more context? 
If you could provide a copy of the JSON it would be very useful.

**Comment by jamietdavidson** [comment]
Hi @tyronbrand !

I have changed my transaction to take in more (albiet primitive) types, in an attempt to dodge this issue altogether. I suppose more generally, I am unable to specify a Struct as an input type into a transaction, specifically one that was imported from a deployed contract.

I went through all of the examples, and I found that none of them included passing in a complex struct to a transaction. It's worth noting, that I haven't been able to find a transaction example on flows main repository page that documents this either, so i'm not sure whether it's even possible.

What would be helpful, were I to try this again, would be:
1. Having an example(s) of passing in a complex struct to a transaction.
2. Having the ability to pass in arguments to the Constructors of the classes that derive from `ICadence`. I found myself having to do `someCadenceVariable.Value = ...`, when I wished I could have just passed it directly into the constructor.

Overall, I am very impressed with the library - thank you for your hard work.

**Comment by jamietdavidson** [comment]
Fixed it!

For anyone who is running into this, I had to wrap things in `CadenceOptional`, whereas I was passing in `null`. @tyronbrand, would it be possible to raise an exception in this case to guide the user towards correct usage? I want to say I spent roughly 3 days on this, so any help for future developers would be awesome :).

**Comment by tyronbrand** [comment]
Nice work @jamietdavidson. I will make the changes you suggested :)
