### ISSUE TITLE
Blocoto Wallet Account Proof

### ISSUE THREAD

**Issue by SIAOYUCHEN** [tyronbrand/flow.net#102]
Hi
I would like to do blocoto account wallet proof
I found example on Js
Could you tell me how to implment it on .net sdk or give me some direction??

https://testnet.flowscan.org/contract/A.5b250a8a85b44a67.BloctoCrypto

import {AppUtils} from '@onflow/fcl'

// as of fcl@^1.0.0
const isSignatureValid = await AppUtils.verifyAccountProof(
  appIdentifier,
  {
    address,
    nonce,
    signatures,
  },
  {
    fclCryptoContract: BLOCTO_FCLCRYPTO_CONTRACT_ADDRESS
  }
)

// as of fcl@0.0.79
const isSignatureValid = const isValid = await fcl.verifyUserSignatures(
  message,
  signatures,
  {
    fclCryptoContract: BLOCTO_FCLCRYPTO_CONTRACT_ADDRESS
  }
)

**Comment by tyronbrand** [comment]
Hopefully, this will help https://github.com/tyronbrand/fcl.net/blob/a7bd8abf1ce6b21594686f457e7a9e3e5fd41c16/src/Fcl.Net.Core/Fcl.cs#L108

**Comment by SIAOYUCHEN** [comment]
Thanks, I Will take a try
It look very hopeful
