### ISSUE TITLE
Connection Issues

### ISSUE THREAD

**Issue by univexnet** [tyronbrand/flow.net#107]
Greetings, been a while, worked great, built a tool around your library and everything went fine, until day or two ago, seems like it is not even possible to connect to Flow chain on my end, Http nor gRpc client work for me, 

![obrazek](https://github.com/tyronbrand/flow.net/assets/10500562/d97cdaad-8294-4d81-b2e4-de6421b282a9)

As for http client, it apparently connects, but GetEventsForBlockheightAsync is crashing with a null error (seems like client is null, so maybe no really connecting) - these errors came with no edits on my end, so probably onflow changed something I'm missing here?

Have a nice day & thanks for reading,
Martin

**Comment by tyronbrand** [comment]
Hey,
There was maintenance yesterday and the day before on Mainnet. Could it have been around then?

**Comment by univexnet** [comment]
Hello, it's happening even now, not sure really what I messed up. gRpc client won't connect at all, and as for http there's issues with getting events, as on screenshot below:
![obrazek](https://github.com/tyronbrand/flow.net/assets/10500562/4f7afcef-6649-4d68-af6f-3d07b3ffcdc8)

It's in Czech, but error is simply saying there was a null reference, for some reason.

**Comment by tyronbrand** [comment]
Thanks for the info. I will investigate and get back to you!

**Comment by univexnet** [comment]
Not sure if any useful info to you, but my other project with GUI built with .NET 7 & WPF is connecting without any issues, the code is 1:1 same for Flow.Net part, so it may be possible it's something related to the schema in gRpc + framework versions, I believe I had this issue before but you somehow managed to fix it.

Anyway, thanks a bunch for taking the time to look into it.

**Comment by tyronbrand** [comment]
I haven't been able to reproduce the issue with gRpc but I did get an issue with the HTTP Client which I have just pushed in a fix for. Hopefully, it will fix the issue you're having with the HTTP Client.

**Comment by univexnet** [comment]
It indeed fixed the issues with http version, will swap to http, as that works great, the gRpc is probably related to the .net framework version, my bad for being lazy to rewrite it to newer .NET, haha.

Thanks again for your patience & willingness to assist me and have a nice rest of the day,
Martin
