### ISSUE TITLE
ResourceExhausted status returned when we call execute "FlowClientAsync.ExecuteTemplateScriptAtLatestBlockAsync"

### ISSUE THREAD

**Issue by noumankhan645** [tyronbrand/flow.net#61]
Previously Application was working fine. Since morning when i call the scripts at "FlowClientAsync.ExecuteTemplateScriptAtLatestBlockAsync" it is giving us error. the status code is ResourceExhausted
see below the full exception.
_"at Flow.Net.Sdk.Client.FlowClientAsync.ExecuteTemplateScriptAtLatestBlockAsync(ByteString script, IEnumerable`1 arguments, CallOptions options) in /app/Infrastructure/Flow.Net.SDK/Client/FlowClientAsync.cs:line 262Status(StatusCode="ResourceExhausted", Detail="", DebugException="Grpc.Core.Internal.CoreErrorDetailException: {"created":"@1645016479.875410921","description":"Error received from peer ","file":"/var/local/git/grpc/src/core/lib/surface/call.cc","file_line":1070,"grpc_message":"","grpc_status":8}")"_

Also 1 more important thing, we are facing this issue only on deployed application. on local it is working fine. 

Can you please help me on that. Thanks
![image](https://user-images.githubusercontent.com/82152638/154278082-569b3e4f-630b-4eca-82de-10e70d7151e2.png)

**Comment by tyronbrand** [comment]
Where you running this against Mainnet? or Testnet?
I think Mainnet went down for 2 hours today.

**Comment by noumankhan645** [comment]
we are on mainnet. and still facing the issue..

**Comment by tyronbrand** [comment]
You should be able to pass gRpc ChannelOptions eg.

```
var grpcOptions = new List<ChannelOption>
{
    new ChannelOption(ChannelOptions.MaxReceiveMessageLength, 8 * 1024 * 1024)
};
var flowClient = new FlowClientAsync("Mainnet", options: grpcOptions);
```

There is also a new release available with the latest gRpc packages.

**Comment by noumankhan645** [comment]
Made the suggested changes, also update the package but issue still persists.

**Comment by tyronbrand** [comment]
Closing as this thread has been inactive for some time. I hope you managed to resolve your issue.
