### ISSUE TITLE
Not able to grab some events, probably my own mistake

### ISSUE THREAD

**Issue by univexnet** [tyronbrand/flow.net#72]
Heya,

first of all, thanks for this wonderful library! I'm sadly having an issue getting events out of one contract and not sure why, tried with [DCoding64's SDK](https://github.com/DCoding64) which gets the events correctly, but sadly the library is missing other functions I'd like to use, so just trying my luck here. :)

Example Event I'm trying to get is [here](https://flowscan.org/transaction/3a860fd4995ffaa3730649b4f391ff0bf586fbb93c399496cd014638634e7b9e) I'm aiming for the ListingAvailable or ListingCreated, that shouldn't matter (none of these two work). Maybe the Type: Optional is the issue here and I'm missing something / misusing the library?

I'm actually detecting the event occuring, but after looping through event.Events its empty, count is 0 and your PrintEvents function is
not printing any results back (obviously, it's empty :D)

Not working code: 
```
internal class FlowExplorer
    {
        private const string LISTING_EVENT = "A.4eb8a10cb9f87357.NFTStorefront.ListingAvailable";
        private const string WITHDRAW_EVENT = "A.329feb3ab062d289.UFC_NFT.Withdraw";
        private const string DEPOSIT_EVENT = "A.329feb3ab062d289.UFC_NFT.Deposit";
        private const string TOKENS_WITHDRAWN = "A.ead892083b3e2c6c.DapperUtilityCoin.TokensWithdrawn";

        FlowClientAsync client;
        public FlowExplorer()
        {
            client = new FlowClientAsync("access.mainnet.nodes.onflow.org:9000");

        }

        public async Task Scan()
        {
            await client.PingAsync();
            while (true)
            {
                try
                {
                    

                    var block = await client.GetLatestBlockAsync();

                    var events = await client.GetEventsForHeightRangeAsync(LISTING_EVENT, block.Height - 1, block.Height);
                    if (events.Count() > 0)
                    {
                        Log("Events are present");
                        
                    }
                    foreach (var e in events)
                    {
                        if (e.@Events.Count > 0)
                        {
                            Log("Got them all");
                        }
                    }
                    PrintEvents(events);
                    await Task.Delay(1000);
                }
                catch (Exception FlowException) { await Task.Delay(1000);  /*Log(FlowException.Message);*/ }
            }

        }
        private static void PrintEvents(IEnumerable<FlowBlockEvent> flowBlockEvents)
        {
            foreach (var blockEvent in flowBlockEvents)
                PrintEvent(blockEvent.Events);
        }

        private static void PrintEvent(IEnumerable<FlowEvent> flowEvents)
        {
            foreach (var @event in flowEvents)
            {
                Console.WriteLine($"Type: {@event.Type}");
                Console.WriteLine($"Values: {@event.Payload.Encode()}");
                Console.WriteLine($"Transaction ID: {@event.TransactionId.FromByteStringToHex()} \n");
            }
        }
        static void Log(string x)
        {
            Console.WriteLine(x);
        }

    }
```

Working Code: (Different contract + event)
```
    internal class FlowExplorer
    {
        private const string LISTING_EVENT = "A.4eb8a10cb9f87357.NFTStorefront.ListingAvailable";
        private const string WITHDRAW_EVENT = "A.329feb3ab062d289.UFC_NFT.Withdraw";
        private const string DEPOSIT_EVENT = "A.329feb3ab062d289.UFC_NFT.Deposit";
        private const string TOKENS_WITHDRAWN = "A.ead892083b3e2c6c.DapperUtilityCoin.TokensWithdrawn";

        FlowClientAsync client;
        public FlowExplorer()
        {
            client = new FlowClientAsync("access.mainnet.nodes.onflow.org:9000");

        }

        public async Task Scan()
        {
            await client.PingAsync();
            while (true)
            {
                try
                {
                    

                    var block = await client.GetLatestBlockAsync();

                    var events = await client.GetEventsForHeightRangeAsync(WITHDRAW_EVENT, block.Height - 1, block.Height);
                    if (events.Count() > 0)
                    {
                        Log("Events are present");
                        
                    }
                    foreach (var e in events)
                    {
                        if (e.Events.Count > 0)
                        {
                            Log("Got them all");
                        }
                    }
                    PrintEvents(events);
                    await Task.Delay(1000);
                }
                catch (Exception FlowException) { await Task.Delay(1000);  /*Log(FlowException.Message);*/ }
            }

        }
        private static void PrintEvents(IEnumerable<FlowBlockEvent> flowBlockEvents)
        {
            foreach (var blockEvent in flowBlockEvents)
                PrintEvent(blockEvent.Events);
        }

        private static void PrintEvent(IEnumerable<FlowEvent> flowEvents)
        {
            foreach (var @event in flowEvents)
            {
                Console.WriteLine($"Type: {@event.Type}");
                Console.WriteLine($"Values: {@event.Payload.Encode()}");
                Console.WriteLine($"Transaction ID: {@event.TransactionId.FromByteStringToHex()} \n");
            }
        }
        static void Log(string x)
        {
            Console.WriteLine(x);
        }
    }
```
This is a working screenshot on **A.329feb3ab062d289.UFC_NFT.Withdraw**
![working](https://user-images.githubusercontent.com/10500562/176460290-8bd6b3bd-5ffd-49c0-a00b-c00057b868ed.png)
This is not working - **A.4eb8a10cb9f87357.NFTStorefront.ListingAvailable**
![not_working](https://user-images.githubusercontent.com/10500562/176459845-8bec5419-6894-493f-b428-158412a37453.png)

As you can see, it detects that there are events (the address is correct) but is not able to gather event details, any clue what am I doing wrong here? 

Sorry for disturbing & have a nice day,
UniveX

**Comment by tyronbrand** [comment]
Hey,

I have just published a fix, could you please upgrade to v0.6.1 and try again?

**Comment by univexnet** [comment]
Hello, thanks for the quick reply! Sadly, I've updated to 0.6.1 and the issue seems to be the same, Event is being detected, but I am not able to parse the event.Events (it returns 0 as a count)
![sadlyno](https://user-images.githubusercontent.com/10500562/176505550-d2da01d0-bfc9-4100-b573-2d4b45dd3d1e.png)
.

**Comment by univexnet** [comment]
To add to previous, event ListingAvailable kind of works(?) See below image:
![w1](https://user-images.githubusercontent.com/10500562/176539413-9f50ca05-20c8-4679-823d-9cc27738b53b.png)
But ListingCreated is still coming out as empty, any clue what could be different?

![nw1](https://user-images.githubusercontent.com/10500562/176539474-85224925-b9f8-4a83-9625-a8710906cd41.png)

**Comment by univexnet** [comment]
Not sure how, but probably your recent update fixed this, all of sudden running it two hours later with no changes from my side and it's working, so we can mark it as fixed :) Thanks a lot, keep up the good work!

**Comment by tyronbrand** [comment]
Hey,
Here is the sample i used(based on your example): (https://github.com/tyronbrand/flow-help/tree/main/FlowHelp3)

If you have any other problems then please open a new issue.
