### ISSUE TITLE
Legacy gRPC

### ISSUE THREAD

**Issue by flostellbrink** [tyronbrand/flow.net#74]
Hey! Thanks for the great library!

Ran into an issue today with the [Grpc.Core](https://www.nuget.org/packages/Grpc.Core) package.
It is still using the native library but doesn't provide one for osx-arm64. Which is a bit of a hassle when developing on an M1 mac.

The [official recommendation](https://grpc.io/blog/grpc-csharp-future/) is to use [Grpc.Net.Client](https://www.nuget.org/packages/Grpc.Net.Client/) which uses pure C# only.

Are you interested in making that transition?
If so are you looking for contributions?

Edit: My current workaround is installing this [Contrib.Grpc.Core.M1](https://www.nuget.org/packages/Contrib.Grpc.Core.M1) but that doesn't feel ideal.

**Comment by flostellbrink** [comment]
HTTP client would definitely work for me! Thanks for the quick response :)

**Comment by script-money** [comment]
Meet the same problem in Unity3D, I hope HTTP feature release soon
