### ISSUE TITLE
FlowHelp #3

### ISSUE THREAD

**Issue by univexnet** [tyronbrand/flow.net#78]
Heya, sorry to disturb again, tried running your example and for some reason, I'm able to grab most of ListingAvailable events, but even with your example, I start to receive a lot of exceptions (attached screenshot) and that leads to missing some listings, like 1 out of 10 is missed and when it is missed, this exception comes up: 
![exception](https://user-images.githubusercontent.com/10500562/177600944-d90f0edf-f3cb-4d53-a163-724fc46e8a67.png)

Tried to log transaction id so I could send you a flowscan link, but sadly, since it crashes on GetEventsForHeightRangeAsync I'am not even able to grab the transaction id. Contract is still the same (I literally ran your example you sent me few days ago). 
A.4eb8a10cb9f87357.NFTStorefront.ListingAvailable

Any clue what am I missing?

Have a nice day,
Uni

**Comment by univexnet** [comment]
Yup, seems to be running for 10-60 seconds with no issues, after that timespan, it starts only throwing errors and sometimes grabs a correct event. It varies, sometimes it runs for 1 second, sometimes for 2 minutes, sometimes not at all.
![1](https://user-images.githubusercontent.com/10500562/177615224-6a1f2c7a-3832-4599-bf21-a9ce727f6262.png)
![2](https://user-images.githubusercontent.com/10500562/177615231-4285d08b-f980-45e0-bbec-6873dc81bbf3.png)
![3](https://user-images.githubusercontent.com/10500562/177615321-a6db5706-aeef-456e-8c4d-97598e817798.png)

As on attached screenshots, ran flawlessly for around 30 seconds, then this happens.


Thanks again for looking into it.

**Comment by tyronbrand** [comment]
Thanks for the info. 
I have located the issue. It seems to be that converter as suspected.
I don't want to put in a hacky fix so give me a day or two and it should be resolved.

**Comment by univexnet** [comment]
No worries, take your time! :) And thanks again, I'm glad on one side that it wasn't my fault, on the other hand not that glad that I caused you additional trouble. :D

Don't forget to send some sort of a link, where I could donate you some bucks for beer atleast.


Have a nice rest of the day,
Uni

**Comment by tyronbrand** [comment]
The [example](https://github.com/tyronbrand/flow-help/tree/main/FlowHelp3) has been updated. I have recently pushed in a fix so haven't been testing it for too long but it looks promising.

If you hit any problems, please update this issue.

**Comment by tyronbrand** [comment]
Great, I will close this issue. If you have any other issues please create a new one.
